name: Deploy to Amazon ECS

on:
  push:
    branches:
      - prod

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Prod to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/backend
            git pull origin prod
            pm2 delete fity_prod || true
            npm install
            npx prisma db push --accept-data-loss
            npm run build
            pm2 start dist/main.js --name fity_prod
